#!/usr/bin/env ruby

require_relative 'lib/contest'

session = chrome_session


username = ARGV.shift || "ciccio1@example.com"

registrati(session, username)
fai_login(session, username)

articolo = primo_articolo_di_yahoo(session)

sottoponi_un_articolo(session,
                      "andrea-francia-#{articolo[:titolo]}",
                      articolo[:contenuto][0..1000])

session.save_and_open_page